spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

general:
  kafka-topic: midas-core

logging:
  level:
    root: INFO
    com.jpmc.midascore: DEBUG


